=== yonas255/Look-up-product-XML/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Products">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Product" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Description" type="DescriptionType"/>
            </xs:sequence>
            <xs:attribute name="Code" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="DescriptionType">
    <xs:sequence>
      <xs:element name="Category" type="xs:string"/>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="DescriptionText" type="xs:string"/>
      <xs:element name="Quantity" type="xs:integer"/>
      <xs:element name="UnitPrice" type="xs:decimal"/>
      <xs:element name="Image" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== yonas255/Look-up-product-XML/product.xml
<Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <Product Code="000-01">
        <Description>
            <Category>Category 1</Category>
            <Name>Nike Runnere 1</Name>
            <DescriptionText>Comfy Nike shoes 1 .</DescriptionText>
            <Quantity>10</Quantity>
            <UnitPrice>200.99</UnitPrice>
            <Image>img/nike17.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-02">
        <Description>
            <Category>Category 2</Category>
            <Name>Nike Runnere 2</Name>
            <DescriptionText>Comfy Nike shoes 2 .</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>95.49</UnitPrice>
            <Image>img/nike4.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-03">
        <Description>
            <Category>Category 3</Category>
            <Name>Air Force Nike</Name>
            <DescriptionText>Comfy Nike shoes 3.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>105.49</UnitPrice>
            <Image>img/nike5.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-04">
        <Description>
            <Category>Category 4</Category>
            <Name>Nike Runner 3</Name>
            <DescriptionText>Comfy Nike shoes 4.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>115.49</UnitPrice>
            <Image>img/nike21.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-05">
        <Description>
            <Category>Category 5</Category>
            <Name>Nike Runner 4</Name>
            <DescriptionText>Comfy Nike shoes 5.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>15.49</UnitPrice>
            <Image>img/nike7.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-06">
        <Description>
            <Category>Category 6</Category>
            <Name>Nike Air Max</Name>
            <DescriptionText>Comfy Nike shoes 6.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>15.49</UnitPrice>
            <Image>img/nike8.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-07">
        <Description>
            <Category>Category 7</Category>
            <Name>Nike Runner 5</Name>
            <DescriptionText>Comfy Nike shoes 7.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>115.49</UnitPrice>
            <Image>img/nike9.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-08">
        <Description>
            <Category>Category 8</Category>
            <Name>Air Max pro</Name>
            <DescriptionText>Comfy Nike shoes 8.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>100.49</UnitPrice>
            <Image>img/nike10.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-09">
        <Description>
            <Category>Category 9</Category>
            <Name>Air Jordan</Name>
            <DescriptionText>Comfy Nike shoes 9.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>120.49</UnitPrice>
            <Image>img/nike11.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-10">
        <Description>
            <Category>Category 10</Category>
            <Name>Jordan Pro</Name>
            <DescriptionText>Comfy Nike shoes 10.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>215.49</UnitPrice>
            <Image>img/nike12.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-11">
        <Description>
            <Category>Category 11</Category>
            <Name>Nike Runner 6</Name>
            <DescriptionText>Comfy Nike shoes 11.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>115.49</UnitPrice>
            <Image>img/nike13.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-12">
        <Description>
            <Category>Category 12</Category>
            <Name>Nike Jordan pro</Name>
            <DescriptionText>Comfy Nike shoes 12.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>105.49</UnitPrice>
            <Image>img/nike20.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-13">
        <Description>
            <Category>Category 13</Category>
            <Name>Nike pro</Name>
            <DescriptionText>Comfy Nike shoes 13.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>155.49</UnitPrice>
            <Image>img/nike15.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-14">
        <Description>
            <Category>Category 14</Category>
            <Name>Nike Runner 7</Name>
            <DescriptionText>Comfy Nike shoes 14.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>199.49</UnitPrice>
            <Image>img/nike18.jpg</Image>
        </Description>
    </Product>
    <Product Code="000-15">
        <Description>
            <Category>Category 15</Category>
            <Name>Air Jordan 2</Name>
            <DescriptionText>Comfy Nike shoes 15.</DescriptionText>
            <Quantity>15</Quantity>
            <UnitPrice>95.49</UnitPrice>
            <Image>img/nike19.jpg</Image>
        </Description>
	</Product>
</Products>
